language: swift
osx_image: xcode7.3
branches:
  only:
    - master
env:
- LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
script:
- set -o pipefail
before_script: 
- gem install xcpretty

script:
- xcodebuild -project ExampleSwift/ExampleSwift.xcodeproj -scheme ExampleSwift -sdk iphonesimulator test | xcpretty -c
- pod lib lint --quick